FROM python:3.10-slim
 
ENV PYTHONUNBUFFERED True
 
RUN apt-get update && apt-get install -y \
  git \
  tesseract-ocr \
  tesseract-ocr-eng \
  tesseract-ocr-ara \
  tesseract-ocr-fra \
  && rm -rf /var/lib/apt/lists/*
 
RUN useradd -m -u 10001 appuser
 
WORKDIR /app
 
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . /app
 
ENV HF_HOME=/tmp/huggingface
ENV TRANSFORMERS_CACHE=/tmp/huggingface
 
USER appuser
 
ENV PORT=8080
EXPOSE 8080
 
CMD exec uvicorn app:app --host 0.0.0.0 --port $PORT
